<a href="https://colab.research.google.com/github/dyyland23-glitch/Marketing-sales-data/blob/main/marketing_Run%20simple%20linear%20regression%20(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity: Run simple linear regression

## **Introduction**


As you're learning, simple linear regression is a way to model the relationship between two variables. By assessing the direction and magnitude of a relationship, data professionals are able to uncover patterns and transform large amounts of data into valuable knowledge. This enables them to make better predictions and decisions.

In this lab, you are part of an analytics team that provides insights about your company's sales and marketing practices. You have been assigned to a project that focuses on the use of influencer marketing. For this task, you will explore the relationship between your radio promotion budget and your sales.

The dataset provided includes information about marketing campaigns across TV, radio, and social media, as well as how much revenue in sales was generated from these campaigns. Based on this information, company leaders will make decisions about where to focus future marketing resources. Therefore, it is critical to provide them with a clear understanding of the relationship between types of marketing campaigns and the revenue generated as a result of this investment.

## **Step 1: Imports**

Import relevant Python libraries and modules.

In [4]:
# Import relevant Python libraries and modules.

import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

from bs4 import BeautifulSoup
import requests

The dataset provided is a .csv file (named `marketing_sales_data.csv`), which contains information about marketing conducted in collaboration with influencers, along with corresponding sales. Assume that the numerical variables in the data are expressed in millions of dollars. As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

**Note:** This is a fictional dataset that was created for educational purposes and modified for this lab.

In [5]:
# RUN THIS CELL TO IMPORT YOUR DATA.

### YOUR CODE HERE ###
url = "https://raw.githubusercontent.com/dyyland23-glitch/Marketing-sales-data/main/marketing_sales_data.csv"
data = pd.read_csv(url)

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

Refer to what you learned about loading data in Python.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

There is a function in the `pandas` library that allows you to read data from a .csv file and load the data into a DataFrame.


</details>

<details>
  <summary><h4><strong>Hint 3</strong></h4></summary>

Use the `read_csv()` function from the `pandas` library.

</details>

## **Step 2: Data exploration**

To get a sense of what the data includes, display the first 10 rows of the data.

In [6]:
# Display the first 10 rows of the data.

data.head(10)

       TV      Radio  Social Media Influencer       Sales
0     Low   1.218354      1.270444      Micro   90.054222
1  Medium  14.949791      0.274451      Macro  222.741668
2     Low  10.377258      0.061984       Mega  102.774790
3    High  26.469274      7.070945      Micro  328.239378
4    High  36.876302      7.618605       Mega  351.807328
5    High  25.561910      5.459718      Micro  261.966812
6    High  37.263819      6.886535       Nano  349.861575
7     Low  13.187256      2.766352      Macro  140.415286
8    High  29.520170      2.333157       Nano  264.592233
9     Low   3.773287      0.135074       Nano   55.674214

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

Refer to what you learned about exploring datasets in Python.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function in the `pandas` library that allows you to get a specific number of rows from the top of a DataFrame.


</details>

<details>
  <summary><h4><strong>Hint 3</strong></h4></summary>

Use the `head()` function from the `pandas` library.

</details>

**Question:** What do you observe about the different variables included in the data?


the ROIs vary widly overall ranging from 90 millions to 351 millions

 identify the number of rows and the number of columns.

In [9]:
# Display number of rows, number of columns.

len(data)

572

In [13]:
data.shape

(572, 5)

**Question:** How many rows and columns exist in the data?


(572, 5)

check for missing values in the rows and columns
Use the .isna() attribute


**False: The cell has valid data (it is not missing).**

**True: The cell is empty or missing (NaN).**


 Missing values are useless when modeling the relationship between two variables. (Cant be done )

In [14]:
# Start with .isna() to get booleans indicating whether each value in the data is missing.

# data.isna(): Converts every cell into a boolean, returning True if the value
# is missing (NaN) and False if it contains data.

data.isna()


# ANY rows containing missing values (NaN) are hidden inside the collapsed middle
# section (rows 5 to 566). SEE NEXT CODE

        TV  Radio  Social Media  Influencer  Sales
0    False  False         False       False  False
1    False  False         False       False  False
2    False  False         False       False  False
3    False  False         False       False  False
4    False  False         False       False  False
..     ...    ...           ...         ...    ...
567  False  False         False       False  False
568  False  False         False       False  False
569  False  False         False       False  False
570  False  False         False       False  False
571  False  False         False       False  False

[572 rows x 5 columns]

In [24]:
# data.isna().any(axis=1).sum()
# Counts the total number of rows
# that contain at least one missing value.
# Use .sum() to get the number of rows that contain missing values.

data.isna().any(axis=1).sum()

np.int64(3)

In [26]:

#How to see the exact 3 rows with missing values
#To filter and display only the rows where NaN exists,
# run A BOOLEAN  this in a new cell:

data[data.isna().any(axis=1)]


data[data.isna().any(axis=1)]

       TV      Radio  Social Media Influencer       Sales
232   NaN  34.111674      4.624148       Nano  342.913372
443  High  36.466753      5.635992       Mega         NaN
510   Low        NaN      4.132526      Macro   78.031498

In [21]:
# data.isna().any(axis=1)
# checks: Whether a value is missing or NaN (NaN / null).


# A value of 0 is completely valid data to .isna(), so 0 evaluates to False (not missing).
# It only returns True if a row has a blank, missing cell or (NaN).


data.isna().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
567    False
568    False
569    False
570    False
571    False
Length: 572, dtype: bool

The result above confirms that my blank or NaN cells
are hidden inside the collapsed middle
section (rows 5 to 566)

**Question:** How many rows containing missing values?

x3 rows

Next, drop the rows that contain missing values.

Data cleaning makes your data more usable for analysis and regression.

Then, check to make sure that the resulting data does not contain any rows with missing values.


### use dropna() attribute

In [33]:
# Use .dropna(axis=0) to indicate that you want rows which contain missing values to be dropped.
data.dropna(axis=0)

         TV      Radio  Social Media Influencer       Sales
0       Low   1.218354      1.270444      Micro   90.054222
1    Medium  14.949791      0.274451      Macro  222.741668
2       Low  10.377258      0.061984       Mega  102.774790
3      High  26.469274      7.070945      Micro  328.239378
4      High  36.876302      7.618605       Mega  351.807328
..      ...        ...           ...        ...         ...
567    High  28.210738      4.373466      Micro  302.887998
568  Medium  23.578661      2.856657       Mega  232.555023
569     Low   9.169824      0.067279       Nano   73.888838
570     Low  11.563403      1.727947       Nano  121.949570
571  Medium  18.814801      3.440682       Mega  182.511614

[569 rows x 5 columns]

In [34]:

# To update the DataFrame, reassign it to the result.

data = data.dropna(axis=0)

The next step for this task is checking model assumptions.
1.
2.
3.
4.


To explore the relationship between radio promotion  and sales,
model the relationship using linear regression.


 Begin by confirming whether the model assumptions for linear regression can be made in this context.


**Note:** Some of the assumptions can be addressed before the model is built. and smoe after

Create a plot of pairwise relationships in the data. This will help you visualize the relationships and check model assumptions.

In [ ]:
# Create plot of pairwise relationships.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video section about creating a plot that shows the relationships between pairs of variables.

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function in the `seaborn` library that you can call to create a plot that shows the
  relationships between pairs of variables.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `pairplot()` function from the `seaborn` library.

</details>

**Question:** Is the assumption of linearity met?

[Write your response here. Double-click (or enter) to edit.]

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video section about checking model assumptions for linear regression.

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  Use the scatterplot of `Sales` over `Radio` found in the preceding plot of pairwise relationships.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

  Check the scatterplot of `Sales` over `Radio` found in the plot of pairwise relationships. If the data points cluster around a line, that indicates that the assumption of linearity is met. Alternatively, if the data points resemble a random cloud or a curve, then a linear model may not fit the data.  

</details>

## **Step 3: Model building**

Select only the columns that are needed for the model.

In [ ]:
# Select relevant columns.
# Save resulting DataFrame in a separate variable to prepare for regression.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about selecting multiple columns from a DataFrame.

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  Use two pairs of square brackets around the names of the columns that should be selected.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

  Make sure column names are spelled exactly as they are in the data.

</details>

Now, display the first 10 rows of the new DataFrame to better understand the data.

In [ ]:
# Display first 10 rows of the new DataFrame.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about displaying contents of a DataFrame.

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function in the `pandas` library that allows you to display the first n number of rows of a DataFrame, where n is a number of your choice.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

  Call the `head()` function from the `pandas` library and pass in the number of rows from the top that you want to display.

</details>

Next, write the linear regression formula for modeling the relationship between the two variables of interest.

In [ ]:
# Write the linear regression formula.
# Save it in a variable.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video section where model building for linear regression is discussed.

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  Save the formula as string.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

  Use a tilde to separate the y variable from the x variable so that the computer understands which is which. Make sure the spelling of each variable exactly matches the corresponding column from the data.

</details>

Now, implement the ordinary least squares (OLS) approach for linear regression.

In [ ]:
# Implement OLS.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video that discusses model building for linear regression.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `statsmodels` library that can be called to implement OLS.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

  You can call the `ols()` function from the `statsmodels` library.

</details>

Now, create a linear regression model for the data and fit the model to the data.

In [ ]:
# Fit the model to the data.
# Save the fitted model in a variable.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video section where model building for linear regression is discussed.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `statsmodels` library that can be called to fit the model.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `fit()` function from the `statsmodels` library.

</details>

## **Step 4: Results and evaluation**

Begin by getting a summary of the results from the model.

In [ ]:
# Get summary of results.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

You may find it helpful to refer back to the video section where getting model results is discussed.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `statsmodels` library that can be called to get the summary of results from a model.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `summary()` function from the `statsmodels` library.

</details>

Next, analyze the bottom table from the results summary. Based on the table, identify the coefficients that the model determined would generate the line of best fit. The coefficients are the y-intercept and the slope.

**Question:** What is the y-intercept?

[Write your response here. Double-click (or enter) to edit.]

**Question:** What is the slope?

[Write your response here. Double-click (or enter) to edit.]

**Question:** What linear equation would you write to express the relationship between sales and radio promotion budget? Use the form of y = slope * x + y-intercept?

[Write your response here. Double-click (or enter) to edit.]

**Question:** What does the slope mean in this context?

[Write your response here. Double-click (or enter) to edit.]

Now that you've built the linear regression model and fit it to the data, finish checking the model assumptions. This will help confirm your findings. First, plot the OLS data with the best fit regression line.

In [ ]:
# Plot the OLS data with the best fit regression line.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about plotting data with the best fit regression line.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `seaborn` library that can be useful here.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `regplot()` function from the `seaborn` library.

</details>

**Question:** What do you observe from the preceding regression plot?

[Write your response here. Double-click (or enter) to edit.]

Now, check the normality assumption. Get the residuals from the model.

In [ ]:
# Get the residuals from the model.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about accessing residuals.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is an attribute from the `statsmodels` library that can be called to get the residuals from a fitted model.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `resid` attribute from the `statsmodels` library.

</details>

Now, visualize the distribution of the residuals.

In [ ]:
# Visualize the distribution of the residuals.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about visualizing residuals.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `seaborn` library that can be called to create a histogram.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `histplot()` function from the `seaborn` library.

</details>

**Question:** Based on the visualization, what do you observe about the distribution of the residuals?

[Write your response here. Double-click (or enter) to edit.]

Next, create a Q-Q plot to confirm the assumption of normality.

In [ ]:
# Create a Q-Q plot.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about creating a Q-Q plot.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `statsmodels` library that can be called to create a Q-Q plot.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `qqplot()` function from the `statsmodels` library.

</details>

**Question:** Is the assumption of normality met?

[Write your response here. Double-click (or enter) to edit.]

Now, check the assumptions of independent observation and homoscedasticity. Start by getting the fitted values from the model.

In [ ]:
# Get fitted values.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about calculating fitted values.  

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `statsmodels` library that can be called to calculate fitted values from the model.

</details>

<details>
<summary><h4><strong>Hint 3</strong></h4></summary>

Call the `predict()` function from the `statsmodels` library. Make sure to pass in the column from `ols_data` corresponding to the x variable.

</details>

Next, create a scatterplot of the residuals against the fitted values.

In [ ]:
# Create a scatterplot of residuals against fitted values.

### YOUR CODE HERE ###

<details>
<summary><h4><strong>Hint 1</strong></h4></summary>

Refer to the video about visualizing residuals against fitted values.

</details>

<details>
<summary><h4><strong>Hint 2</strong></h4></summary>

  There is a function from the `seaborn` library that can be called to create a scatterplot.

</details>

<details>
  <summary><h4>Hint 3</h4></summary>

Call the `scatterplot()` function from the `seaborn` library.

</details>

**Question:** Are the assumptions of independent observation and homoscedasticity met?

[Write your response here. Double-click (or enter) to edit.]

## **Considerations**

**What are some key takeaways that you learned during this lab?**

[Write your response here. Double-click (or enter) to edit.]

**How would you present your findings from this lab to others?**

[Write your response here. Double-click (or enter) to edit.]

**What summary would you provide to stakeholders?**

[Write your response here. Double-click (or enter) to edit.]

**References**

[Pandas.DataFrame.Any — Pandas 1.4.3 Documentation.](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.any.html)

[Pandas.DataFrame.Isna — Pandas 1.4.3 Documentation.](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html)

[Pandas.Series.Sum — Pandas 1.4.3 Documentation.](https://pandas.pydata.org/docs/reference/api/pandas.Series.sum.html)

[Saragih, H.S. *Dummy Marketing and Sales Data*.](https://www.kaggle.com/datasets/harrimansaragih/dummy-advertising-and-sales-data)

**Congratulations!** You've completed this lab. However, you may not notice a green check mark next to this item on Coursera's platform. Please continue your progress regardless of the check mark. Just click on the "save" icon at the top of this notebook to ensure your work has been logged.